model: gpt-4o-mini
max_tokens: 3000
rate_limit: 5000  # tokens/min global
prompt_overflow_strategy: split
child_limit:
  max_depth: 4
  max_children_per_manager: 8
retries: 3
backoff_base_s: 2
log_retention_days: 14
